.\" Manpage for waku.
.\" Contact waku@google.com for further insights not covered in this manual.
.TH man 7 "18 March 2018" "0.0" "waku manpage"
.SH NAME
.B waku
\- waku 
.SH SYNOPSIS
.B waku
[\fIOPTION\fR]... [\fIMESSAGE\fR]
.SH DESCRIPTION
.B waku
mesages waku with \fIMESSAGE\fR.
.PP
Requires waku to work properly.
Ask your admin.
.SH OPTIONS
.B waku
takes one optional option.
.TP
\fB\-n\fR, \fB\-\-nay\fR 
Negate \fIMESSAGE\fR.
.br
Deprecated.  \fIMESSAGE\fR will be received negatively either way.
.SH SEE ALSO
hmm(1), wut(2), nix(9) 
.SH BUGS
None whatsoever.
.SH AUTHOR
waku (waku@google.com)
